return {
  icons = {
    mode = "󱔎",
    file = "󰈚",
    git_added = "",
    git_changed = "",
    git_removed = "",
    git_branch = "",
    lsp = "",
    copilot = "󱜙",
    diagnostics_error = "",
    diagnostics_warn = "",
    diagnostics_hint = "󰛩",
    diagnostics_info = "󰋼",
    cwd = "",
    cursor = "",
    lsp_progress = { "", "", "", "󰪞", "󰪟", "󰪠", "󰪢", "󰪣", "󰪤", "󰪥" },
    separator = { left = "", right = "" },
  },
  statusline_order = { "mode", "file", "git", "%=", "lsp_msg", "%=", "diagnostics", "lsp", "cwd", "cursor" },
}
