return {
  groups = {
    find = "<leader>f",
    git = "<leader>g",
    ui = "<leader>u",
    language = "<leader>l",
    neovim = "<leader>v",
  },
  top = {
    smart = "<leader><space>",
    buffer = "<leader>,",
    grep = "<leader>/",
    command_history = "<leader>:",
    notification = "<leader>n",
    explorer = "<leader>e",
    scratch = "<leader>.",
    select_scratch = "<leader>S",
    local_keys = "<leader>?",
  },
  find = {
    buffers = "<leader>fb",
    config = "<leader>fc",
    files = "<leader>ff",
    git_files = "<leader>fg",
    projects = "<leader>fp",
    recent = "<leader>fr",
  },
  git = {
    blame_line = "<leader>gB",
    lazygit = "<leader>gL",
    hunk_inline = "<leader>gh",
    branches = "<leader>gb",
    log = "<leader>gl",
    status = "<leader>gs",
    stash = "<leader>gS",
    diff = "<leader>gd",
    log_file = "<leader>gf",
  },
  ui = {
    dim = "<leader>uD",
    indent = "<leader>ui",
    inlay_hints = "<leader>uh",
    treesitter = "<leader>ut",
    diagnostics = "<leader>ud",
    line_number = "<leader>ul",
    background = "<leader>ub",
    wrap = "<leader>uw",
    scroll = "<leader>us",
    zen = "<leader>uz",
    zoom = "<leader>uZ",
    colorscheme = "<leader>uc",
  },
  language = {
    format = "<leader>lf",
  },
}
